name: .NET Core and Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set environment variable
      run: export DOTNET_SYSTEM_THREADING_POOLASYNCVALUETASKS=1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.6
    - name: Install dependencies
      working-directory: ./c#-async-io
      run: dotnet restore
    - name: dotnet Build
      working-directory: ./c#-async-io
      run: dotnet build --configuration Release --no-restore
    - name: dotnet Run
      working-directory: ./c#-async-io/bin/Release
      run: ./c#-async-io
    - name: Rust Build
      working-directory: ./rust-async-io
      run: cargo build --release --verbose
    - name: Rust Run
      working-directory: ./rust-async-io/target/release
      run: ./rust-async-io
